# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCTV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomName', models.CharField(max_length=20)),
                ('Ip', models.CharField(max_length=20)),
                ('InfoPort', models.CharField(max_length=5)),
                ('CamPort', models.CharField(max_length=5)),
            ],
        ),
    ]
